// ! 1ST PROGRAM
#include<iostream>
using namespace std;
int main()
{
    // cout: it is use for print anything in programing language
    cout<<"hemlo___!! ";
    // endl are use for new line
    cout<<endl;
    cout<<"\n";
    // return 0 : program is successfully execute
    return 0;
}

// ! TAKING INPUT AND PRINT 
#include<iostream>
using namespace std;
int main()
{
    int variable;
    cout<<"enter the value in variable : ";
    // take input by cin;
    cin>>variable;
    // print anything by cout
    cout<<variable;
}
